global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    static_configs:
      - targets: ['api:3000']

  - job_name: 'converter'
    static_configs:
      - targets: ['converter:8082']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
